server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xxm9513/spring-cloud-study.git
          searchPaths: configDir
          username: xxm9513
          password: xiaoming9513
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/